### ISSUE TITLE
Is there a way to add images to show off while running the program?

### ISSUE THREAD

**Issue by YoungSquidoo** [Aethese/Switchence#1]
Hello!

I was just wondering on how to add images to showcase the games I am playing while running the program and Discord together?

**Comment by YoungSquidoo** [comment]
Oh nevermind, I was just actually asking specifically about Monster Hunter Rise. It doesn't show an image when I run the program but the other games too.

I was wondering now if this would be fixed in the next update?

**Comment by Aethese** [comment]
Oh never notice this problem, I will work on a fix asap!
