### ISSUE TITLE
[Needs added] Game request

### ISSUE THREAD

**Issue by SnipexTV** [Aethese/Switchence#18]
Hi,

Kirby™ and the Forgotten Land would be nice the demo is already playable

thank u and nice tool.

**Comment by Aethese** [comment]
When the game comes out I'll add it lol. I'll keep this open until it officially releases though.

**Comment by LukeIsHereToDevelop** [comment]
It just came out. Can you add it?
Would be cool :)

**Comment by Aethese** [comment]
added, will be published online in the next hour (at the most)
