### ISSUE TITLE
Game Request

### ISSUE THREAD

**Issue by Raijingeki** [Aethese/Switchence#30]
Hi! I have come again for some game requests of quite popular games XD

- Fire Emblem Warriors: Three Hopes
- Live A Live
- Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles
- TRIANGLE STRATEGY
- Pokémon Legends: Arceus

Appreciate all the work and updates so far!

**Comment by Aethese** [comment]
hello so here are my responses to your games:
* alright i'll add this
* sadly i'm going to have to say this game isn't big enough to add in the current game list, it will have to wait until v2.0.0
* all right i can add this too
* i will add this too
* this game has already been added lol

so my final response is i'll be adding `Fire Emblem Warriors: Three Hopes`, `Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles`, and `TRIANGLE STRATEGY`

**Comment by Raijingeki** [comment]
Oh, didn't realize about Arceus lol. Anyways, thanks! Can't wait for the next update

**Comment by Aethese** [comment]
added them
