### ISSUE TITLE
Game Request: NieR:Automata The End of YoRHa Edition

### ISSUE THREAD

**Issue by GLPG35** [Aethese/Switchence#39]
I already did a pull request to the current list so the only thing left to do is merge it. But the only thing left is the image right here:
![nier-automata](https://user-images.githubusercontent.com/55563130/195235039-d5078217-f50f-4ebc-9c01-c731fd23e837.jpg)

**Comment by Aethese** [comment]
looks good to me, closing this issue in favor of #38
