### ISSUE TITLE
Game Request

### ISSUE THREAD

**Issue by marcintomala** [Aethese/Switchence#42]
Pokémon Scarlet 

and 

Pokémon Violet

Thank you 🙂

**Comment by Aethese** [comment]
Ok, I'll add these as soon as I'm on my computer

**Comment by Aethese** [comment]
sorry for the long wait, I've been busy for the past couple of days. I'll add them after I get off work in about 11 hours or so

**Comment by Aethese** [comment]
added, and again sorry for the wait

**Comment by marcintomala** [comment]
No worries, it was quick :) Thank you so much!
