### ISSUE TITLE
Game Request

### ISSUE THREAD

**Issue by Raijingeki** [Aethese/Switchence#6]
Hello! A huge fan of your work! I was wondering if you could also include some of these games:

Diablo II: Resurrected
Diablo III: Eternal Collection
NEO: The World Ends With You
Shadowverse: Champion's Battle
Monster Hunter Stories 2: Wings of Ruin
Bravely Default II
No More Heroes III

Apologies if it's too much. Looking forward to your next update!

**Comment by Aethese** [comment]
That should be fine! I'll all of those as soon as possible!

**Comment by Raijingeki** [comment]
Awesome! Thank you so much!

**Comment by Aethese** [comment]
Sorry for the delay but I have added all the games you have requested. If you feel a change should be made, feel free to reopen this issue.
