### ISSUE TITLE
More Game Requests

### ISSUE THREAD

**Issue by Raijingeki** [Aethese/Switchence#8]
Hello again Aethese! Here again for another request lol. I was hoping if you could add some of these games:

- Super Robot Wars 30
- Samurai Warriors 5
- Shin Megami Tensei V
- Pokemon Brilliant Diamond / Shining Pearl
- World of Final Fantasy Maxima
- Cardfight Vanguard EX
- Monster Hunter Stories 2
- Astral Chain
- Star Ocean First Departure R
- Tokyo Mirage Sessions #FE Encore

Apologies if it is a bit too many and if some of them are already included in your upcoming games update as well.

Appreciate all the work that you do!

**Comment by Aethese** [comment]
yeah I'll add these in the next upcoming Switchence update which should be releasing in the near future.

**Comment by Raijingeki** [comment]
Awesome, can't wait for it soon enough :)

**Comment by Aethese** [comment]
although the pokemon games have not come out yet, i have added them :p

the game list update will be coming out shortly along with v1.9.0. i will close this issue when it actually releases

**Comment by Aethese** [comment]
released the update. heads up: some of your games i didn't include into the game list because i've never heard of them, sorry about that! just want more well known games on the list to not clutter it up too much.

**Comment by Raijingeki** [comment]
All good. :) Just tested it and the favorite function makes things even better. Thanks a lot!

**Comment by Aethese** [comment]
glad you like it :)
